-- PostgreSQL / Supabase uniquement. Migration non executee.
-- AI_HANDOFF / TODO_DATABASE : schema prepare, pas encore raccorde au PHP.
-- Ne pas executer sans verifier le schema reel et remplacer les placeholders.
-- Les scripts 001 a 006 du depot sont en dialecte MySQL, pas une base PostgreSQL fiable.
-- TODO_AUTH : definir les droits SQL/RLS selon le mode d'acces Supabase retenu
-- avant toute exposition via son API ; aucune politique d'acces n'est installee ici.
-- Pas de trigger : updated_at et l'historique devront etre geres cote serveur.
-- AVANT EXECUTION : remplacer chaque __UTILISATEUR_ID_TYPE__ dans les
-- migrations 007 a 009 par le type SQL exact de public.utilisateur.id.
-- Ce placeholder est volontairement non resolu : ne pas deduire ce type
-- de la migration MySQL 001 presente dans le depot.
-- Verifier aussi le schema public, le nom de la table utilisateur et
-- l'existence d'une cle primaire ou unique sur utilisateur.id.
-- Ordre d'execution prevu : 007, puis 008, puis 009.
-- Remplacer aussi __ZONE_ID_TYPE__ par le type SQL exact de public.zone.id
-- et verifier que cette colonne possede une cle primaire ou unique.

BEGIN;

CREATE TABLE public.ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    utilisateur_id __UTILISATEUR_ID_TYPE__ NOT NULL,
    assigne_a_id __UTILISATEUR_ID_TYPE__ NULL,
    zone_id __ZONE_ID_TYPE__ NULL,
    titre VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    statut VARCHAR(50) NOT NULL DEFAULT 'ouvert',
    a_prioriser_rapidement BOOLEAN NOT NULL DEFAULT FALSE,
    priorite VARCHAR(50) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMPTZ NULL,

    CONSTRAINT pk_ticket PRIMARY KEY (id),
    CONSTRAINT fk_ticket_utilisateur FOREIGN KEY (utilisateur_id)
        REFERENCES public.utilisateur(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ticket_assigne_a FOREIGN KEY (assigne_a_id)
        REFERENCES public.utilisateur(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ticket_zone FOREIGN KEY (zone_id)
        REFERENCES public.zone(id) ON DELETE RESTRICT
);

COMMENT ON COLUMN public.ticket.utilisateur_id IS
    'Utilisateur qui cree et possede le ticket.';
COMMENT ON COLUMN public.ticket.assigne_a_id IS
    'Futur agent support ; NULL tant que le ticket est non attribue.';
COMMENT ON COLUMN public.ticket.a_prioriser_rapidement IS
    'Urgence signalee par le demandeur, retirable par le support apres examen.';
COMMENT ON COLUMN public.ticket.priorite IS
    'Priorite definie par le support ; NULL tant que le ticket reste a qualifier.';
COMMENT ON COLUMN public.ticket.zone_id IS
    'Zone concernee facultative ; NULL si la demande ne concerne aucune zone.';
COMMENT ON COLUMN public.ticket.updated_at IS
    'A actualiser explicitement lors des modifications ; aucun trigger installe.';

CREATE INDEX idx_ticket_utilisateur_created_at
    ON public.ticket (utilisateur_id, created_at DESC, id DESC);
CREATE INDEX idx_ticket_statut_updated_at
    ON public.ticket (statut, updated_at DESC, id DESC);
CREATE INDEX idx_ticket_assigne_a_statut
    ON public.ticket (assigne_a_id, statut);
CREATE INDEX idx_ticket_priorite_updated_at
    ON public.ticket (priorite, updated_at DESC, id DESC);
CREATE INDEX idx_ticket_updated_at
    ON public.ticket (updated_at DESC, id DESC);
CREATE INDEX idx_ticket_zone
    ON public.ticket (zone_id);

CREATE INDEX idx_ticket_a_prioriser_rapidement
    ON public.ticket (created_at, id) WHERE a_prioriser_rapidement = TRUE;

COMMIT;
