-- PostgreSQL / Supabase uniquement. Migration non executee.
-- AI_HANDOFF / TODO_BACKEND : raccorder les notes internes locales a cette table.
-- Les echanges publics ne sont pas encore implementes ; filtrer interne cote serveur.
-- L'auteur devra venir de la session ; verifier le droit d'acces au ticket parent.
-- Prerequis : migration 007_create_ticket.sql.
-- AVANT EXECUTION : remplacer __UTILISATEUR_ID_TYPE__ par le type SQL exact
-- de public.utilisateur.id, comme dans 007 et 009. Verifier le schema public
-- et le nom de la table utilisateur ; aucun type utilisateur n'est suppose.

BEGIN;

CREATE TABLE public.ticket_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ticket_id BIGINT NOT NULL,
    auteur_id __UTILISATEUR_ID_TYPE__ NOT NULL,
    contenu TEXT NOT NULL,
    interne BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_ticket_message PRIMARY KEY (id),
    CONSTRAINT fk_ticket_message_ticket FOREIGN KEY (ticket_id)
        REFERENCES public.ticket(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ticket_message_auteur FOREIGN KEY (auteur_id)
        REFERENCES public.utilisateur(id) ON DELETE RESTRICT
);

CREATE INDEX idx_ticket_message_ticket_created_at
    ON public.ticket_message (ticket_id, created_at, id);
CREATE INDEX idx_ticket_message_auteur
    ON public.ticket_message (auteur_id);

COMMIT;
