-- PostgreSQL / Supabase uniquement. Migration non executee.
-- AI_HANDOFF / TODO_BACKEND : remplacer l'historique local JS par ces insertions,
-- dans la transaction du ticket ; acteur_id provient de la session authentifiee.
-- Prerequis : migration 007_create_ticket.sql ; a appliquer apres 008.
-- AVANT EXECUTION : remplacer __UTILISATEUR_ID_TYPE__ par le type SQL exact
-- de public.utilisateur.id, comme dans 007 et 008. Verifier le schema public
-- et le nom de la table utilisateur ; aucun type utilisateur n'est suppose.

BEGIN;

CREATE TABLE public.ticket_historique (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ticket_id BIGINT NOT NULL,
    acteur_id __UTILISATEUR_ID_TYPE__ NOT NULL,
    champ VARCHAR(100) NOT NULL,
    ancienne_valeur TEXT NULL,
    nouvelle_valeur TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_ticket_historique PRIMARY KEY (id),
    CONSTRAINT fk_ticket_historique_ticket FOREIGN KEY (ticket_id)
        REFERENCES public.ticket(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ticket_historique_acteur FOREIGN KEY (acteur_id)
        REFERENCES public.utilisateur(id) ON DELETE RESTRICT
);

COMMENT ON TABLE public.ticket_historique IS
    'Historique a alimenter dans la meme transaction que la modification du ticket.';
COMMENT ON COLUMN public.ticket_historique.ancienne_valeur IS
    'Valeur precedente sous forme textuelle ; NULL si aucune valeur precedente.';
COMMENT ON COLUMN public.ticket_historique.nouvelle_valeur IS
    'Nouvelle valeur sous forme textuelle ; NULL si la valeur est retiree.';

CREATE INDEX idx_ticket_historique_ticket_created_at
    ON public.ticket_historique (ticket_id, created_at, id);
CREATE INDEX idx_ticket_historique_acteur
    ON public.ticket_historique (acteur_id);

COMMIT;
